chi2fcn_per_point_breakdown_yaml_to_py = {
    "IdPoint": "id_point",
    "IDDataSet": "id_dataset",
    "Chi2": "chi2",
    "Data": "data",
    "Theo": "theory",
    "KinVarVals": "kinetic_variables",
    "TypeExp": "type_experiment",
    "FSHadron": "final_state_hadron",
}

kinvars_yaml_to_py = {
    "BIN": "id_bin",
    "RS": "sqrt_s",
    "X": "x",
    "Y": "y",
    "Q2": "Q2",
    "W2": "W2",
    "EHAD": "E_had",
    "PT": "pT",
    "PTMIN": "pT_min",
    "PTMAX": "pT_max",
    "Y": "y",
    "YMIN": "y_min",
    "YMAX": "y_max",
    "ETA": "eta",
    "ETAMIN": "eta_min",
    "ETAMAX": "eta_max",
    "XI_R": "xi_r",
    "XI_F": "xi_f",
}

kinvars_py_to_tex = {
    "id_bin": r"\text{bin}",
    "sqrt_s": r"\sqrt{s}",
    "Q2": r"Q^2",
    "x": r"x",
    "y": r"y",
    "pT": r"p_{\text{T}}",
    "pT_min": r"p_{\text{T}}",
    "pT_max": r"p_{\text{T}}",
    "y": r"y",
    "y_min": r"y",
    "y_max": r"y",
    "eta": r"\eta",
    "eta_min": r"\eta",
    "eta_max": r"\eta",
    "xi_r": r"\xi_{\text{r}}",
    "xi_f": r"\xi_{\text{f}}",
}

theory_yaml_to_py = {
    "SIG": "sigma",
    "RSIG": "ratio_sigma",
    "SIGIPT": "sigma_pT_integrated",
    "F2": "F2",
    "RF2": "ratio_F2",
    "APPLGRID": "applgrid",
    "RAPPLGRID": "rapplgrid",
}

theory_py_to_tex = {
    "sigma": r"\sigma",
    "ratio_sigma": r"\dfrac{\sigma^{A}}{\sigma^{\text{D}}}",
    "F2": r"F_2",
    "ratio_F2": r"\dfrac{F_2^{A}}{F_2^{\text{D}}}",
}

uncertainties_yaml_to_py = {
    "STAT": "unc_stat",
    "SYSU": "unc_sys",
    "SYST": "unc_tot",
    "THEO": "unc_theo",
    "EPS": "unc_eps", # ? e.g. in ccfrXmuNu3_791.yaml
    "CORP": "unc_corp"  # ? e.g. in chorxsNb2_5947.yaml
}

data_yaml_to_py = {
    **kinvars_yaml_to_py,
    **theory_yaml_to_py,
    **uncertainties_yaml_to_py,
}

parameters_cj15_py_to_tex = {
    "kappa": r"\kappa",
    "c": "c",
    "uv_p1": r"p_1^{u_v}",
    "uv_p2": r"p_2^{u_v}",
    "uv_p3": r"p_3^{u_v}",
    "uv_p4": r"p_4^{u_v}",
    "uv_p5": r"p_5^{u_v}",
    "uv_a1": r"a_1^{u_v}",
    "uv_a2": r"a_2^{u_v}",
    "uv_a3": r"a_3^{u_v}",
    "uv_a4": r"a_4^{u_v}",
    "uv_a5": r"a_5^{u_v}",
    "uv_b1": r"b_1^{u_v}",
    "uv_b2": r"b_2^{u_v}",
    "uv_b3": r"b_3^{u_v}",
    "uv_b4": r"b_4^{u_v}",
    "uv_b5": r"b_5^{u_v}",
    "dv_p1": r"p_1^{d_v}",
    "dv_p2": r"p_2^{d_v}",
    "dv_p3": r"p_3^{d_v}",
    "dv_p4": r"p_4^{d_v}",
    "dv_p5": r"p_5^{d_v}",
    "dv_p6": r"p_6^{d_v}",
    "dv_a1": r"a_1^{d_v}",
    "dv_a2": r"a_2^{d_v}",
    "dv_a3": r"a_3^{d_v}",
    "dv_a4": r"a_4^{d_v}",
    "dv_a5": r"a_5^{d_v}",
    "dv_a6": r"a_6^{d_v}",
    "dv_b1": r"b_1^{d_v}",
    "dv_b2": r"b_2^{d_v}",
    "dv_b3": r"b_3^{d_v}",
    "dv_b4": r"b_4^{d_v}",
    "dv_b5": r"b_5^{d_v}",
    "dv_b6": r"b_6^{d_v}",
    "ubdb_p1": r"p_1^{u̅+d̅}",
    "ubdb_p2": r"p_2^{u̅+d̅}",
    "ubdb_p3": r"p_3^{u̅+d̅}",
    "ubdb_p4": r"p_4^{u̅+d̅}",
    "ubdb_p5": r"p_5^{u̅+d̅}",
    "ubdb_a1": r"a_1^{u̅+d̅}",
    "ubdb_a2": r"a_2^{u̅+d̅}",
    "ubdb_a3": r"a_3^{u̅+d̅}",
    "ubdb_a4": r"a_4^{u̅+d̅}",
    "ubdb_a5": r"a_5^{u̅+d̅}",
    "ubdb_b1": r"b_1^{u̅+d̅}",
    "ubdb_b2": r"b_2^{u̅+d̅}",
    "ubdb_b3": r"b_3^{u̅+d̅}",
    "ubdb_b4": r"b_4^{u̅+d̅}",
    "ubdb_b5": r"b_5^{u̅+d̅}",
    "ssbsum_p0": r"p_0^{s+s̅}",
    "ssb_p1": r"p_1^{s+s̅}",
    "ssb_p2": r"p_2^{s+s̅}",
    "ssb_p3": r"p_3^{s+s̅}",
    "ssb_p4": r"p_4^{s+s̅}",
    "ssb_p5": r"p_5^{s+s̅}",
    "ssbsum_a0": r"a_0^{s+s̅}",
    "ssb_a1": r"a_1^{s+s̅}",
    "ssb_a2": r"a_2^{s+s̅}",
    "ssb_a3": r"a_3^{s+s̅}",
    "ssb_a4": r"a_4^{s+s̅}",
    "ssb_a5": r"a_5^{s+s̅}",
    "ssbsum_b0": r"b_0^{s+s̅}",
    "ssb_b1": r"b_1^{s+s̅}",
    "ssb_b2": r"b_2^{s+s̅}",
    "ssb_b3": r"b_3^{s+s̅}",
    "ssb_b4": r"b_4^{s+s̅}",
    "ssb_b5": r"b_5^{s+s̅}",
    "gsum_p0": r"p_0^{g}",
    "g_p1": r"p_1^{g}",
    "g_p2": r"p_2^{g}",
    "g_p3": r"p_3^{g}",
    "g_p4": r"p_4^{g}",
    "g_p5": r"p_5^{g}",
    "gsum_a0": r"a_0^{g}",
    "g_a1": r"a_1^{g}",
    "g_a2": r"a_2^{g}",
    "g_a3": r"a_3^{g}",
    "g_a4": r"a_4^{g}",
    "g_a5": r"a_5^{g}",
    "gsum_b0": r"b_0^{g}",
    "g_b1": r"b_1^{g}",
    "g_b2": r"b_2^{g}",
    "g_b3": r"b_3^{g}",
    "g_b4": r"b_4^{g}",
    "g_b5": r"b_5^{g}",
    "dboub_p0": r"p_0^{d̅/u̅}",
    "dboub_p1": r"p_1^{d̅/u̅}",
    "dboub_p2": r"p_2^{d̅/u̅}",
    "dboub_p3": r"p_3^{d̅/u̅}",
    "dboub_p4": r"p_4^{d̅/u̅}",
    "dboub_p5": r"p_5^{d̅/u̅}",
    "dboub_a0": r"a_0^{d̅/u̅}",
    "dboub_a1": r"a_1^{d̅/u̅}",
    "dboub_a2": r"a_2^{d̅/u̅}",
    "dboub_a3": r"a_3^{d̅/u̅}",
    "dboub_a4": r"a_4^{d̅/u̅}",
    "dboub_a5": r"a_5^{d̅/u̅}",
    "dboub_b0": r"b_0^{d̅/u̅}",
    "dboub_b1": r"b_1^{d̅/u̅}",
    "dboub_b2": r"b_2^{d̅/u̅}",
    "dboub_b3": r"b_3^{d̅/u̅}",
    "dboub_b4": r"b_4^{d̅/u̅}",
    "dboub_b5": r"b_5^{d̅/u̅}",
}
